import React, { useState } from "react";
import CategoryFilter from "../Components/CategoryFilter";
import ProductCard from "../Components/ProductCard";

const Products = () => {
  const allProducts = [
    {
      id: 1,
      name: "Natural Boadywash - Kumkumadi",
      category: "Boadywash",
      price: 299,
      rating: 4.8,
      description: "Gentle natural bodywash with kumkumadi extract",
      image: "/assets/Boadywash/Bw1.png",
      badge: "Best Seller",
    },
    {
      id: 2,
      name: "Natural Boadywash - Detan",
      category: "Boadywash",
      price: 299,
      rating: 4.7,
      description: "Soothing detan bodywash",
      image: "/assets/Boadywash/Bw2.png",
      badge: "Popular",
    },
    {
      id: 3,
      name: "Natural Boadywash - Kojic Acid",
      category: "Boadywash",
      price: 299,
      rating: 4.9,
      description: "Brightening kojic acid bodywash",
      image: "/assets/Boadywash/Bw3.png",
      badge: "New",
    },
    {
      id: 4,
      name: "Natural Boadywash - Manjistha",
      category: "Boadywash",
      price: 299,
      rating: 4.8,
      description: "Relaxing manjistha bodywash",
      image: "/assets/Boadywash/Bw4.png",
      badge: "Best Seller",
    },
    {
      id: 5,
      name: "Natural Boadywash - Vitamin C",
      category: "Boadywash",
      price: 299,
      rating: 4.7,
      description: "Refreshing vitamin C boadywash",
      image: "/assets/Boadywash/Bw5.png",
      badge: "Best Seller",
    },
    {
      id: 6,
      name: "Gentle Face Wash - Advanced Herbal",
      category: "FaceWash",
      price: 399,
      rating: 4.8,
      description: "Creamy face wash for sensitive skin",
      image: "/assets/FaceWash/FW1.png",
      badge: "Best Seller",
    },
    {
      id: 7,
      name: "Hydrate and nourish Face Wash - Goat Milk",
      category: "FaceWash",
      price: 399,
      rating: 4.8,
      description: "Hydrating face wash enriched with goat milk",
      image: "/assets/FaceWash/FW2.png",
      badge: "Best Seller",
    },
    {
      id: 8,
      name: "Revitalization and nourish Face Wash - Kumkumadi",
      category: "FaceWash",
      price: 399,
      rating: 4.8,
      description: "Revitalizing kumkumadi face wash",
      image: "/assets/FaceWash/FW3.png",
      badge: "Best Seller",
    },
    {
      id: 9,
      name: "Detoxifying and Soothing Face Wash - Kuppaimeni",
      category: "FaceWash",
      price: 399,
      rating: 4.8,
      description: "Detoxifying face wash with kuppaimeni",
      image: "/assets/FaceWash/FW4.png",
      badge: "Best Seller",
    },
    {
      id: 10,
      name: "Clean and brightening Face Wash - Manjistha",
      category: "FaceWash",
      price: 399,
      rating: 4.8,
      description: "Brightening manjistha face wash",
      image: "/assets/FaceWash/FW5.png",
      badge: "Best Seller",
    },
    {
      id: 11,
      name: "Revitalizing and brightening Face Wash - RedWine",
      category: "FaceWash",
      price: 349,
      rating: 4.8,
      description: "Revitalizing red wine face wash",
      image: "/assets/FaceWash/FW6.png",
      badge: "Best Seller",
    },
    {
      id: 12,
      name: "Rejuvenating and Glowing Face Wash - Saffron",
      category: "FaceWash",
      price: 349,
      rating: 4.8,
      description: "Luxurious saffron face wash for glowing skin",
      image: "/assets/FaceWash/FW7.png",
      badge: "Best Seller",
    },
    {
      id: 13,
      name: "Detox and purify - Charcoal",
      category: "FaceWash",
      price: 349,
      rating: 4.8,
      description: "Deep cleansing charcoal face wash",
      image: "/assets/FaceWash/FW8.png",
      badge: "Best Seller",
    },
    {
      id: 14,
      name: "Advanced Anti-aging Gel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Advanced anti-aging botanical face gel",
      image: "/assets/Facegel/Fg1.png",
      badge: "Best Seller",
    },
    {
      id: 15,
      name: "Aloe vera Face gel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Soothing aloe vera face gel",
      image: "/assets/Facegel/Fg2.png",
      badge: "Best Seller",
    },
    {
      id: 16,
      name: "Kumkumadi face gel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Radiance-boosting kumkumadi face gel",
      image: "/assets/Facegel/Fg3.png",
      badge: "Best Seller",
    },
    {
      id: 17,
      name: "Manjistha Facegel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Skin-clarifying manjistha face gel",
      image: "/assets/Facegel/Fg4.png",
      badge: "Best Seller",
    },
    {
      id: 18,
      name: "Pomegranate Facegel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Antioxidant-rich pomegranate face gel",
      image: "/assets/Facegel/Fg5.png",
      badge: "Best Seller",
    },
    {
      id: 19,
      name: "RedWine Facegel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Age-defying red wine face gel",
      image: "/assets/Facegel/Fg6.png",
      badge: "Best Seller",
    },
    {
      id: 20,
      name: "Skin Brightening",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Brightening face gel for even skin tone",
      image: "/assets/Facegel/Fg7.png",
      badge: "Best Seller",
    },
    {
      id: 21,
      name: "Ultra Hydrating gel",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Deep hydration face gel",
      image: "/assets/Facegel/Fg8.png",
      badge: "Best Seller",
    },
    {
      id: 22,
      name: "Vitamin C",
      category: "Facegel",
      price: 349,
      rating: 4.8,
      description: "Brightening vitamin C face gel",
      image: "/assets/Facegel/Fg9.png",
      badge: "Best Seller",
    },
    {
      id: 23,
      name: "Hair Growth oil",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Nourishing hair growth oil",
      image: "/assets/Haircare/Hc1.png",
      badge: "Top Rated",
    },
    {
      id: 24,
      name: "Anti Dandruff Serum",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Effective anti-dandruff serum",
      image: "/assets/Haircare/Hc2.png",
      badge: "Top Rated",
    },
    {
      id: 25,
      name: "Hair Growth serum",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Intensive hair growth serum",
      image: "/assets/Haircare/Hc3.png",
      badge: "Top Rated",
    },
    {
      id: 26,
      name: "Herbal Black - Hair Dye",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Natural herbal black hair dye",
      image: "/assets/Haircare/Hc4.png",
      badge: "Top Rated",
    },
    {
      id: 27,
      name: "Herbal Hair growth oil",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Herbal blend for hair growth",
      image: "/assets/Haircare/Hc5.png",
      badge: "Top Rated",
    },
    {
      id: 28,
      name: "Multi-Protein Shampoo",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Protein-enriched shampoo for strong hair",
      image: "/assets/Haircare/Hc6.png",
      badge: "Top Rated",
    },
    {
      id: 29,
      name: "Rice water conditioner",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Rice water conditioner for shine and softness",
      image: "/assets/Haircare/Hc7.png",
      badge: "Top Rated",
    },
    {
      id: 30,
      name: "Anti Hair fall",
      category: "Haircare",
      price: 499,
      rating: 4.9,
      description: "Strengthening anti-hairfall oil blend",
      image: "/assets/Haircare/Hc8.png",
      badge: "Top Rated",
    },
    {
      id: 31,
      name: "Beetroot Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Moisturizing beetroot lip balm with natural tint",
      image: "/assets/Lipcare/Lc1.png",
      badge: "Popular",
    },
    {
      id: 32,
      name: "Lip scrub",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Exfoliating lip scrub for soft lips",
      image: "/assets/Lipcare/Lc2.png",
      badge: "Popular",
    },
    {
      id: 33,
      name: "Kojic Alpha Arbutin Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Lightening lip balm with kojic acid and alpha arbutin",
      image: "/assets/Lipcare/Lc3.png",
      badge: "Popular",
    },
    {
      id: 34,
      name: "Kojic acid brightening Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Brightening kojic acid lip balm",
      image: "/assets/Lipcare/Lc4.png",
      badge: "Popular",
    },
    {
      id: 35,
      name: "Pineapple Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Tropical pineapple-scented lip balm",
      image: "/assets/Lipcare/Lc5.png",
      badge: "Popular",
    },
    {
      id: 36,
      name: "SPF 50 Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Sun protection lip balm with SPF 50",
      image: "/assets/Lipcare/Lc6.png",
      badge: "Popular",
    },
    {
      id: 37,
      name: "Strawberry Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Sweet strawberry-flavored lip balm",
      image: "/assets/Lipcare/Lc7.png",
      badge: "Popular",
    },
    {
      id: 38,
      name: "Vanilla Lip Balm",
      category: "Lipcare",
      price: 199,
      rating: 4.8,
      description: "Creamy vanilla-scented lip balm",
      image: "/assets/Lipcare/Lc8.png",
      badge: "Popular",
    },
    {
      id: 39,
      name: "Advanced Skin Brightening Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Brightening serum for an even glow",
      image: "/assets/Serum/SE1.png",
      badge: "Popular",
    },
    {
      id: 40,
      name: "Anti-Pigmentation Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Targets pigmentation and dark spots",
      image: "/assets/Serum/SE2.png",
      badge: "Popular",
    },
    {
      id: 41,
      name: "10% Niacinamide Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Oil-control and pore-minimizing serum",
      image: "/assets/Serum/SE3.png",
      badge: "Popular",
    },
    {
      id: 42,
      name: "Skin Brightening Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Radiance-boosting daily serum",
      image: "/assets/Serum/SE4.png",
      badge: "Popular",
    },
    {
      id: 43,
      name: "Kumkumadi Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Traditional glow-enhancing serum",
      image: "/assets/Serum/SE5.png",
      badge: "Popular",
    },
    {
      id: 44,
      name: "10% Glycolic Acid Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Gentle exfoliating serum for smoother skin",
      image: "/assets/Serum/SE6.png",
      badge: "Popular",
    },
    {
      id: 45,
      name: "Ultra Glow Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Instant glow-boosting serum",
      image: "/assets/Serum/SE7.png",
      badge: "Popular",
    },
    {
      id: 46,
      name: "Vitamin C Serum",
      category: "Serum",
      price: 199,
      rating: 4.8,
      description: "Brightening antioxidant serum",
      image: "/assets/Serum/SE8.png",
      badge: "Popular",
    },
    {
      id: 47,
      name: "Advanced Brightening Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Daily brightening cream for even tone",
      image: "/assets/SkinWC/WC1.png",
      badge: "Popular",
    },
    {
      id: 48,
      name: "Anti Pigmentation Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Targets pigmentation and dullness",
      image: "/assets/SkinWC/WC2.png",
      badge: "Popular",
    },
    {
      id: 49,
      name: "Under Eye Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Hydrating cream for under-eye care",
      image: "/assets/SkinWC/WC3.png",
      badge: "Popular",
    },
    {
      id: 50,
      name: "Skin Lightening Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Brightening cream for even complexion",
      image: "/assets/SkinWC/WC4.png",
      badge: "Popular",
    },
    {
      id: 51,
      name: "Red Rice Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Nourishing red rice brightening cream",
      image: "/assets/SkinWC/WC5.png",
      badge: "Popular",
    },
    {
      id: 52,
      name: "Kumkumadi Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Traditional glow-enhancing cream",
      image: "/assets/SkinWC/WC6.png",
      badge: "Popular",
    },
    {
      id: 53,
      name: "De-Tan Glow Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "De-tan cream for brighter skin",
      image: "/assets/SkinWC/WC7.png",
      badge: "Popular",
    },
    {
      id: 54,
      name: "Carrot Manjistha Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Brightening cream with carrot and manjistha",
      image: "/assets/SkinWC/WC8.png",
      badge: "Popular",
    },
    {
      id: 55,
      name: "Berry Brightening Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Berry-rich brightening cream",
      image: "/assets/SkinWC/WC9.png",
      badge: "Popular",
    },
    {
      id: 56,
      name: "Beetroot Glow Cream",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Glow-boosting beetroot cream",
      image: "/assets/SkinWC/WC10.png",
      badge: "Popular",
    },
    {
      id: 57,
      name: "Avocado Brightening",
      category: "SkinWC",
      price: 199,
      rating: 4.8,
      description: "Nourishing avocado brightening cream",
      image: "/assets/SkinWC/WC11.png",
      badge: "Popular",
    },
    {
      id: 58,
      name: "Camel Milk Brightening Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Gentle brightening soap with camel milk",
      image: "/assets/Soap/SP1.png",
      badge: "Popular",
    },
    {
      id: 59,
      name: "Red Wine Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Antioxidant-rich red wine soap",
      image: "/assets/Soap/SP2.png",
      badge: "Popular",
    },
    {
      id: 60,
      name: "Niacinamide Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Brightening soap with niacinamide",
      image: "/assets/Soap/SP3.png",
      badge: "Best Seller",
    },
    {
      id: 61,
      name: "Manjistha Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Herbal manjistha soap for clear skin",
      image: "/assets/Soap/SP4.png",
      badge: "Best Seller",
    },
    {
      id: 62,
      name: "Kumkumadi Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Glow-enhancing kumkumadi soap",
      image: "/assets/Soap/SP5.png",
      badge: "Best Seller",
    },
    {
      id: 63,
      name: "Kojic Acid Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Brightening soap with kojic acid",
      image: "/assets/Soap/SP6.png",
      badge: "Best Seller",
    },
    {
      id: 64,
      name: "Goat Milk Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Moisturizing soap with goat milk",
      image: "/assets/Soap/SP7.png",
      badge: "Best Seller",
    },
    {
      id: 65,
      name: "Donkey Milk Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Gentle nourishing soap with donkey milk",
      image: "/assets/Soap/SP8.png",
      badge: "Best Seller",
    },
    {
      id: 66,
      name: "Detan Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Detan soap for brighter-looking skin",
      image: "/assets/Soap/SP9.png",
      badge: "Popular",
    },
    {
      id: 67,
      name: "Charcoal Soap",
      category: "Soap",
      price: 199,
      rating: 4.8,
      description: "Deep cleansing charcoal soap",
      image: "/assets/Soap/SP10.png",
      badge: "Popular",
    },
  ];

  const [selectedCategory, setSelectedCategory] = useState("All");

  const categories = [
    "All",
    "Boadywash",
    "FaceWash",
    "Facegel",
    "Haircare",
    "Lipcare",
    "Serum",
    "SkinWC",
    "Soap",
  ];

  const filteredProducts =
    selectedCategory === "All"
      ? allProducts
      : allProducts.filter((p) => p.category === selectedCategory);

  return (
    <div className="min-h-screen bg-gradient-to-b from-green-50 via-emerald-50 to-white py-14">
      <div className="max-w-7xl mx-auto px-4">
        <h1 className="text-4xl font-bold text-center text-green-800 mb-3">
          Our Organic Products
        </h1>

        <p className="text-center text-gray-600 mb-12 max-w-2xl mx-auto">
          Discover our carefully crafted range of natural skincare and haircare
          products made with purity, balance, and the power of nature.
        </p>

        <CategoryFilter
          categories={categories}
          selected={selectedCategory}
          onSelect={setSelectedCategory}
        />

        <ProductCard products={filteredProducts} />
      </div>
    </div>
  );
};

export default Products;